In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder,OneHotEncoder
import pickle

In [2]:
data=pd.read_csv("Churn_Modelling.csv")

In [4]:
data.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [5]:
data=data.drop(['CustomerId','RowNumber','Surname'],axis=1)

In [6]:
data.head(2)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [7]:
label_encoder_gender=LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [8]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [14]:
data['Gender'].unique()

array([0, 1])

In [18]:
one_hot_encoder=OneHotEncoder()
geo_encoded=one_hot_encoder.fit_transform(data[['Geography']]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder.get_feature_names_out(['Geography']))

In [19]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [22]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)

In [23]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [30]:
X.shape

(10000, 12)

In [67]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,0,1.0,0.0,0.0

In [26]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [31]:
X_train.shape

(8000, 12)

In [32]:
scalar=StandardScaler()
X_train=scalar.fit_transform(X_train)
X_test=scalar.transform(X_test)

In [33]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [34]:
with open('regression_label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender,file)

In [35]:
with open('regression_one_hot_encoder.pkl', 'wb') as file:
    pickle.dump(one_hot_encoder,file)

In [36]:
with open('regression_scalar.pkl', 'wb') as file:
    pickle.dump(scalar,file)

# Artificial Neural Network With Regression

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [41]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1) #Linewe activation
])

In [42]:
from sklearn import metrics


model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae']) # search keras loss to read the documentation

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [44]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [47]:
import tensorboard
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [50]:
log_dir='regression_log/fit/' +datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [51]:
Early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [53]:
from gc import callbacks


model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[Early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100373.3672 - mae: 100373.3672 - val_loss: 98499.7578 - val_mae: 98499.7578
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99562.9375 - mae: 99562.9375 - val_loss: 96862.5859 - val_mae: 96862.5859
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96718.8984 - mae: 96718.8984 - val_loss: 92694.1719 - val_mae: 92694.1719
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 91150.1406 - mae: 91150.1406 - val_loss: 85789.8828 - val_mae: 85789.8828
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 83111.1016 - mae: 83111.1016 - val_loss: 76975.8984 - val_mae: 76975.8984
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 73758.2188 - mae: 73758.2188 - val_loss: 67954.5391 - val_mae: 67954.5391
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 64853.8242 - mae: 64853.8242 - val_loss: 60401.1797 - val_mae: 60401.1797
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 57935.9570 - mae: 57935.9570 - val_loss: 55153.9023 - val_mae: 55153.9023
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53683.8555 - mae: 53683.8555 - val_loss: 52432.2227 - val_mae: 52432.2227
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51552.2383 - mae: 51552.2383 - val_loss: 51383.7812 - val_mae: 51383.7812
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50695.0312 - mae: 50695.0312 - val_loss: 51011.5039 - val_mae: 51011.5039
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50376.2109 - mae: 50376.2109 - val_loss: 50861.9961 - val_mae: 50861.9961
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50229.8516 - mae: 50229.8516 - val_loss: 50783.2188 - val_mae: 50783.2188
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50150.0391 - mae: 50150.0391 - val_loss: 50726.5078 - val_mae: 50726.5078
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50089.3125 - mae: 50089.3125 - val_loss: 50688.2773 - val_mae: 50688.2773
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50038.5781 - mae: 50038.5781 - val_loss: 50651.4492 - val_mae: 50651.4492
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49998.7656 - mae: 49998.7656 - val_loss: 50616.0586 - val_mae: 50616.0586
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49963.7344 - mae: 49963.7344 - val_loss: 50584.3945 - val_mae: 50584.3945
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49925.4883 - mae: 49925.4883 - val_loss: 50553.2422 - val_mae: 50553.2422
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49895.1211 - mae: 49895.1211 - val_loss: 50528.4141 - val_mae: 50528.4141
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49861.8242 - mae: 49861.8242 - val_loss: 50503.2148 - val_mae: 50503.2148
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49837.9336 - mae: 49837.9336 - val_loss: 50478.8867 - val_mae: 50478.8867
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49813.2773 - mae: 49813.2773 - val_loss: 50468.7344 - val_mae: 50468.7344
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49787.6328 - mae: 49787.6328 - val_loss: 50447.5156 - val_mae: 50447.5156
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49770.1523 - mae: 49770.1523 - val_loss: 50431.8281 - val_mae: 50431.8281
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49749.4219 - mae: 49749.4219 - val_loss: 50415.3359 - val_mae: 50415.3359
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49731.7109 - mae: 49731.7109 - val_loss: 50410.6328 - val_mae: 50410.6328
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49715.3320 - mae: 49715.3320 - val_loss: 50392.3633 - val_mae: 50392.3633
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49700.7617 - mae: 49700.7617 - val_loss: 50390.5234 - val_mae: 50390.5234
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49683.9492 - mae: 49683.9492 - val_loss: 50381.4883 - val_mae: 50381.4883
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49671.8086 - mae: 49671.8086 - val_loss: 50370.8984 - val_mae: 50370.8984
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49655.9062 - mae: 49655.9062 - val_loss: 50362.6992 - val_mae: 50362.6992
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49644.2422 - mae: 49644.2422 - val_loss: 50359.0859 - val_mae: 50359.0859
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49634.3828 - mae: 49634.3828 - val_loss: 50352.4297 - val_mae: 50352.4297
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49618.2461 - mae: 49618.2461 - val_loss: 50340.0273 - val_mae: 50340.0273
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49610.6641 - mae: 49610.6641 - val_loss: 50334.2891 - val_mae: 50334.2891
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49598.8320 - mae: 49598.8320 - val_loss: 50335.8711 - val_mae: 50335.8711
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49589.4648 - mae: 49589.4648 - val_loss: 50330.7852 - val_mae: 50330.7852
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49579.0273 - mae: 49579.0273 - val_loss: 50337.1719 - val_mae: 50337.1719
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49569.2969 - mae: 49569.2969 - val_loss: 50328.4766 - val_mae: 50328.4766
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49559.7930 - mae: 49559.7930 - val_loss: 50324.9688 - val_mae: 50324.9688
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49553.3281 - mae: 49553.3281 - val_loss: 50322.7422 - val_mae: 50322.7422
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49539.6797 - mae: 49539.6797 - val_loss: 50318.9766 - val_mae: 50318.9766
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49532.2891 - mae: 49532.2891 - val_loss: 50327.3828 - val_mae: 50327.3828
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49523.8438 - mae: 49523.8438 - val_loss: 50324.1094 - val_mae: 50324.1094
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518.6133 - mae: 49518.6133 - val_loss: 50329.9805 - val_mae: 50329.9805
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49509.5508 - mae: 49509.5508 - val_loss: 50336.8359 - val_mae: 50336.8359
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49501.0664 - mae: 49501.0664 - val_loss: 50326.5273 - val_mae: 50326.5273
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49496.3633 - mae: 49496.3633 - val_loss: 50332.3086 - val_mae: 50332.3086
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49485.5703 - mae: 49485.5703 - val_loss: 50332.3828 - val_mae: 50332.3828
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49481.5117 - mae: 49481.5117 - val_loss: 50319.2109 - val_mae: 50319.2109
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49470.4805 - mae: 49470.4805 - val_loss: 50335.1445 - val_mae: 50335.1445
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49466.7031 - mae: 49466.7031 - val_loss: 50326.6836 - val_mae: 50326.6836

In [58]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [59]:
%tensorboard --logdir regression_log/fit

Reusing TensorBoard on port 6006 (pid 19884), started 0:00:44 ago. (Use '!kill 19884' to kill it.)

# Evaluation

In [64]:
test_loss,test_mae=model.evaluate(X_test,y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50318.9766 - mae: 50318.9766

In [65]:
test_loss,test_mae

(50318.9765625, 50318.9765625)

In [66]:
model.save('regression_mode.keras')