In [165]:
import tensorflow as tf
from tensorflow.keras.models import load_model

import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [166]:
model=load_model('model.keras')

with open('lebel_encoder_gender.pkl','rb') as file:
    lebel_encoder_gender=pickle.load(file)

with open('onehot_encoder_geo.pkl','rb') as file:
    onehot_encoder_geo=pickle.load(file)

with open('scalar.pkl','rb') as file:
    scalar=pickle.load(file)

In [167]:
input_data = {
    'CreditScore': 800,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 28,
    'Tenure': 5,
    'Balance': 30000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 60000
}

In [168]:
data=pd.DataFrame.from_dict([input_data])

In [169]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,800,France,Male,28,5,30000,2,1,1,60000

In [170]:
onehot_encoder_geo.transform(data[['Geography']]).toarray()

array([[1., 0., 0.]])

In [171]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [172]:

new_data = pd.DataFrame(
    onehot_encoder_geo.transform(data[['Geography']]).toarray(),
    columns=onehot_encoder_geo.get_feature_names_out(['Geography'])
)

In [173]:
data=pd.concat([data,new_data],axis=1)

In [174]:
data=data.drop('Geography',axis=1)

In [175]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,800,Male,28,5,30000,2,1,1,60000,1.0,0.0,0.0

In [176]:
data['Gender']=lebel_encoder_gender.transform(data[['Gender']])

d:\Python_Machine_Learning\Learning\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [177]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,800,1,28,5,30000,2,1,1,60000,1.0,0.0,0.0

In [178]:
data=scalar.transform(data)

In [179]:
data

array([[ 1.53956105e+00,  9.13247552e-01, -1.03607564e+00,
        -1.34471949e-03, -7.38140873e-01,  8.08436154e-01,
         6.49202671e-01,  9.74816989e-01, -7.02965505e-01,
         1.00150113e+00, -5.79467227e-01, -5.76388018e-01]])

In [180]:
prediction=model.predict(data)
print(prediction[0][0])
if prediction[0][0] >= 0.5:
    print("Customer will churn")
else:
    print("Customer will not churn")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
0.0045689098
Customer will not churn